### ISSUE TITLE
Please provide a license

### ISSUE THREAD

**Issue by Extarys** [chefbennyj1/Emby.IntroSkip#7]
When you have 2 minutes, can you please update the repo/upload a license file, whether it's MIT, or GPL or any other.

Nice project! Can't wait to dive into the code, alas my time is currently limited but great job! :heart:

**Comment by chefbennyj1** [comment]
I'll see what I have to do for a licence. The plugin needs an update currently to work with the lastest version on Emby. I haven't had the chance to do it yet. The plugin will break accessing the IFfmpegManager. But I do have a fix.

**Comment by Extarys** [comment]
Ok thanks!

If I have time (lol!) can I clone this and try to adapt it for Jellyfin?
